version: '3'

services:
  postgres:
    image: postgres:10.4
    container_name: my_postgres
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:4.28
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: amgad123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
