export enum EnvEnum {
  DATABASE_URL = 'DATABASE_URL',
  ACCESS_SECRET = 'ACCESS_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
  REFRESH_EXPIRE = 'REFRESH_EXPIRE',
  ACCESS_EXPIRE = 'ACCESS_EXPIRE',
  GOOGLE_DRIVE_NEST_JS_FOLDER = 'GOOGLE_DRIVE_NEST_JS_FOLDER',
  GOOGLE_DRIVE_CLIENT_ID = 'GOOGLE_DRIVE_CLIENT_ID',
  GOOGLE_DRIVE_CLIENT_SECRET = 'GOOGLE_DRIVE_CLIENT_SECRET',
  GOOGLE_DRIVE_REFRESH_TOKEN = 'GOOGLE_DRIVE_REFRESH_TOKEN',
  GOOGLE_DRIVE_REDIRECT_URL_1 = 'GOOGLE_DRIVE_REDIRECT_URL_1',
  GOOGLE_DRIVE_REDIRECT_URL_2 = 'GOOGLE_DRIVE_REDIRECT_URL_2',
}
