name: DOcker image ci for GHRC 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
     name: build_and_publish
     runs-on: ubuntu-latest
     steps:
      - uses : actions/checkout@v3
      - name : Build and push the image 
        run: | 
            docker login --username amgad226 --password ${{secrets.GH_PAT}} ghci.io
            docker build . --tag ghcr.io/amgad226/source-safe:latest
            docker push ghcr.io/amgad226/source-safe:latest  
